_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        OrderedDict([('Agent', array([[100.]], dtype=float32)), ('Display', array([[[[0, 0, 0, ..., 0, 0, 0],
                 [0, 0, 0, ..., 0, 0, 0],
                 [0, 0, 0, ..., 0, 0, 0],
                 ...,
                 [0, 0, 0, ..., 0, 0, 0],
                 [0, 0, 0, ..., 0, 0, 0],
                 [0, 0, 0, ..., 0, 0, 0]],

                [[0, 0, 0, ..., 0, 0, 0],
                 [0, 0, 0, ..., 0, 0, 0],
                 [0, 0, 0, ..., 0, 0, 0],
                 ...,
                 [0, 0, 0, ..., 0, 0, 0],
                 [0, 0, 0, ..., 0, 0, 0],
                 [0, 0, 0, ..., 0, 0, 0]],

                [[0, 0, 0, ..., 0, 0, 0],
                 [0, 0, 0, ..., 0, 0, 0],
                 [0, 0, 0, ..., 0, 0, 0],
                 ...,
                 [0, 0, 0, ..., 0, 0, 0],
                 [0, 0, 0, ..., 0, 0, 0],
                 [0, 0, 0, ..., 0, 0, 0]]]], dtype=uint8))])
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x000001F1E2F04110>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 1000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 13
                - 22
                - 23
                - 35
                - 55
            "4": 3.11.9
            "5": 0.19.11
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
action_noise:
    value: None
action_space:
    value: MultiDiscrete([1600    2    2    2    2    2])
algo:
    value: PPO
batch_size:
    value: 64
clip_range:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x000001F1E2A70540>
clip_range_vf:
    value: None
device:
    value: cuda
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.vec_transpose.VecTransposeImage object at 0x000001F1A911A050>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.3
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x000001F1A9A1F1A0>
max_grad_norm:
    value: 0.5
n_envs:
    value: 1
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: 'Dict(''Agent'': Box(0.0, 100.0, (1,), float32), ''Display'': Box(0, 255, (3, 900, 1600), uint8))'
policy:
    value: |-
        MultiInputActorCriticPolicy(
          (features_extractor): CombinedExtractor(
            (extractors): ModuleDict(
              (Agent): Flatten(start_dim=1, end_dim=-1)
              (Display): NatureCNN(
                (cnn): Sequential(
                  (0): Conv2d(3, 32, kernel_size=(8, 8), stride=(4, 4))
                  (1): ReLU()
                  (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
                  (3): ReLU()
                  (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
                  (5): ReLU()
                  (6): Flatten(start_dim=1, end_dim=-1)
                )
                (linear): Sequential(
                  (0): Linear(in_features=1367296, out_features=256, bias=True)
                  (1): ReLU()
                )
              )
            )
          )
          (pi_features_extractor): CombinedExtractor(
            (extractors): ModuleDict(
              (Agent): Flatten(start_dim=1, end_dim=-1)
              (Display): NatureCNN(
                (cnn): Sequential(
                  (0): Conv2d(3, 32, kernel_size=(8, 8), stride=(4, 4))
                  (1): ReLU()
                  (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
                  (3): ReLU()
                  (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
                  (5): ReLU()
                  (6): Flatten(start_dim=1, end_dim=-1)
                )
                (linear): Sequential(
                  (0): Linear(in_features=1367296, out_features=256, bias=True)
                  (1): ReLU()
                )
              )
            )
          )
          (vf_features_extractor): CombinedExtractor(
            (extractors): ModuleDict(
              (Agent): Flatten(start_dim=1, end_dim=-1)
              (Display): NatureCNN(
                (cnn): Sequential(
                  (0): Conv2d(3, 32, kernel_size=(8, 8), stride=(4, 4))
                  (1): ReLU()
                  (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
                  (3): ReLU()
                  (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
                  (5): ReLU()
                  (6): Flatten(start_dim=1, end_dim=-1)
                )
                (linear): Sequential(
                  (0): Linear(in_features=1367296, out_features=256, bias=True)
                  (1): ReLU()
                )
              )
            )
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=257, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=257, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=1610, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.MultiInputActorCriticPolicy'>
policy_kwargs:
    value: '{}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.DictRolloutBuffer object at 0x000001F1A8D83E50>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.DictRolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1747664501961390200
target_kl:
    value: None
tensorboard_log:
    value: runs/om4899ua
use_sde:
    value: "False"
verbose:
    value: 0
vf_coef:
    value: 0.5
